# Generated by Django 3.1.7 on 2021-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorialrequest',
            name='response',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fibonacirequest',
            name='response',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='powerrequest',
            name='response',
            field=models.FloatField(null=True),
        ),
    ]
