# Generated by Django 3.1.7 on 2021-02-19 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210219_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorialrequest',
            name='index',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='factorialrequest',
            name='response',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fibonacirequest',
            name='index',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fibonacirequest',
            name='response',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='powerrequest',
            name='response',
            field=models.FloatField(blank=True, default=-1),
        ),
    ]
