# Generated by Django 3.1.7 on 2021-02-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210219_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerrequest',
            name='base',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='powerrequest',
            name='exponent',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='powerrequest',
            name='response',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
    ]
