# Generated by Django 3.1.7 on 2021-02-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210219_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerrequest',
            name='base',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='powerrequest',
            name='exponent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='powerrequest',
            name='response',
            field=models.FloatField(default=-1, null=True),
        ),
    ]
