# Generated by Django 3.1.7 on 2021-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210219_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacirequest',
            name='response',
            field=models.PositiveBigIntegerField(default=1, null=True),
        ),
    ]
