# Generated by Django 3.1.7 on 2021-02-20 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210219_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorialrequest',
            name='response',
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fibonacirequest',
            name='index',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
