# Generated by Django 3.1.7 on 2021-02-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210220_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerrequest',
            name='response',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
