# Generated by Django 3.1.7 on 2021-02-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210220_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorialrequest',
            name='response',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fibonacirequest',
            name='response',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
